// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFyfSR6if_2-8KlMdYC2mXWEvF1SDuRwo',
    appId: '1:472340300189:web:8ee0d976627c9564dbef74',
    messagingSenderId: '472340300189',
    projectId: 'expiryease-75692',
    authDomain: 'expiryease-75692.firebaseapp.com',
    storageBucket: 'expiryease-75692.firebasestorage.app',
    measurementId: 'G-TW06ML8C07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtv-NOHCWq4Xmt0GQqQaBT8A7VFB1lF7U',
    appId: '1:472340300189:android:da5ec84e598a9a88dbef74',
    messagingSenderId: '472340300189',
    projectId: 'expiryease-75692',
    storageBucket: 'expiryease-75692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE_ljBL_jzzicaINsDCGYt2ldsrP6iGYE',
    appId: '1:472340300189:ios:48df0fe63a239b0bdbef74',
    messagingSenderId: '472340300189',
    projectId: 'expiryease-75692',
    storageBucket: 'expiryease-75692.firebasestorage.app',
    iosBundleId: 'com.example.smartInventoryAndExpiryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE_ljBL_jzzicaINsDCGYt2ldsrP6iGYE',
    appId: '1:472340300189:ios:48df0fe63a239b0bdbef74',
    messagingSenderId: '472340300189',
    projectId: 'expiryease-75692',
    storageBucket: 'expiryease-75692.firebasestorage.app',
    iosBundleId: 'com.example.smartInventoryAndExpiryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFyfSR6if_2-8KlMdYC2mXWEvF1SDuRwo',
    appId: '1:472340300189:web:1e719500c6366d43dbef74',
    messagingSenderId: '472340300189',
    projectId: 'expiryease-75692',
    authDomain: 'expiryease-75692.firebaseapp.com',
    storageBucket: 'expiryease-75692.firebasestorage.app',
    measurementId: 'G-RX4PBD5S97',
  );
}
